// Auto-generated by Supabase CLI — do not edit manually
// Run `pnpm db:types` to regenerate after schema changes
//
// Manually written for Sprint 0 until we run the migration against
// the remote project and can generate via CLI.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          client_ref: string
          full_name: string
          given_name: string | null
          family_name: string | null
          preferred_name: string | null
          email: string
          phone_e164: string | null
          country_citizenship_iso: string | null
          country_residence_iso: string | null
          timezone: string | null
          preferred_currency: string
          address_id: string | null
          linkedin_url: string | null
          employer: string | null
          job_title: string | null
          field_industry: string | null
          highest_education: string | null
          immigration_goal: string | null
          interested_product: string | null
          how_heard: string | null
          referral_source: string | null
          ambition_statement: string | null
          status: string
          assigned_adviser: string | null
          role: string
          is_founder: boolean
          marketing_consent: boolean
          nda_signed_at: string | null
          nda_signature_name: string | null
          nda_signature_ip: string | null
          nda_signature_ua: string | null
          onboarded_at: string | null
          auth_provider: string
          has_set_password: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          client_ref?: string
          full_name: string
          given_name?: string | null
          family_name?: string | null
          preferred_name?: string | null
          email: string
          phone_e164?: string | null
          country_citizenship_iso?: string | null
          country_residence_iso?: string | null
          timezone?: string | null
          preferred_currency?: string
          address_id?: string | null
          linkedin_url?: string | null
          employer?: string | null
          job_title?: string | null
          field_industry?: string | null
          highest_education?: string | null
          immigration_goal?: string | null
          interested_product?: string | null
          how_heard?: string | null
          referral_source?: string | null
          ambition_statement?: string | null
          status?: string
          assigned_adviser?: string | null
          role?: string
          is_founder?: boolean
          marketing_consent?: boolean
          nda_signed_at?: string | null
          nda_signature_name?: string | null
          nda_signature_ip?: string | null
          nda_signature_ua?: string | null
          onboarded_at?: string | null
          auth_provider?: string
          has_set_password?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          client_ref?: string
          full_name?: string
          given_name?: string | null
          family_name?: string | null
          preferred_name?: string | null
          email?: string
          phone_e164?: string | null
          country_citizenship_iso?: string | null
          country_residence_iso?: string | null
          timezone?: string | null
          preferred_currency?: string
          address_id?: string | null
          linkedin_url?: string | null
          employer?: string | null
          job_title?: string | null
          field_industry?: string | null
          highest_education?: string | null
          immigration_goal?: string | null
          interested_product?: string | null
          how_heard?: string | null
          referral_source?: string | null
          ambition_statement?: string | null
          status?: string
          assigned_adviser?: string | null
          role?: string
          is_founder?: boolean
          marketing_consent?: boolean
          nda_signed_at?: string | null
          nda_signature_name?: string | null
          nda_signature_ip?: string | null
          nda_signature_ua?: string | null
          onboarded_at?: string | null
          auth_provider?: string
          has_set_password?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      addresses: {
        Row: {
          id: string
          profile_id: string | null
          address_line_1: string
          address_line_2: string | null
          city: string
          administrative_area: string | null
          postal_code: string | null
          country_iso: string
          created_at: string
        }
        Insert: {
          id?: string
          profile_id?: string | null
          address_line_1: string
          address_line_2?: string | null
          city: string
          administrative_area?: string | null
          postal_code?: string | null
          country_iso: string
          created_at?: string
        }
        Update: {
          id?: string
          profile_id?: string | null
          address_line_1?: string
          address_line_2?: string | null
          city?: string
          administrative_area?: string | null
          postal_code?: string | null
          country_iso?: string
          created_at?: string
        }
        Relationships: []
      }
      pending_jobs: {
        Row: {
          id: string
          type: string
          payload: Json
          status: string
          run_after: string
          started_at: string | null
          completed_at: string | null
          failed_at: string | null
          error_message: string | null
          attempts: number
          max_attempts: number
          created_at: string
        }
        Insert: {
          id?: string
          type: string
          payload?: Json
          status?: string
          run_after?: string
          started_at?: string | null
          completed_at?: string | null
          failed_at?: string | null
          error_message?: string | null
          attempts?: number
          max_attempts?: number
          created_at?: string
        }
        Update: {
          id?: string
          type?: string
          payload?: Json
          status?: string
          run_after?: string
          started_at?: string | null
          completed_at?: string | null
          failed_at?: string | null
          error_message?: string | null
          attempts?: number
          max_attempts?: number
          created_at?: string
        }
        Relationships: []
      }
      processed_webhooks: {
        Row: {
          id: string
          provider: string
          event_id: string
          event_type: string
          processed_at: string
          result: string
          error_message: string | null
        }
        Insert: {
          id?: string
          provider: string
          event_id: string
          event_type: string
          processed_at?: string
          result: string
          error_message?: string | null
        }
        Update: {
          id?: string
          provider?: string
          event_id?: string
          event_type?: string
          processed_at?: string
          result?: string
          error_message?: string | null
        }
        Relationships: []
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

export type Profile = Database['public']['Tables']['profiles']['Row']
export type Address = Database['public']['Tables']['addresses']['Row']
export type PendingJob = Database['public']['Tables']['pending_jobs']['Row']
export type ProcessedWebhook = Database['public']['Tables']['processed_webhooks']['Row']
